### ISSUE TITLE
what is it？

### ISSUE THREAD

**Issue by bleakie** [avish1993/PosIX-GAN#1]
# Load datasets, default image size 64 x 64
def load_headpose():
    trImages = np.load('trImages.npy')
    trLabel = np.load('trLabel.npy')
    tsImages = np.load('tsImages.npy')
    tsLabel = np.load('tsLabel.npy')
    return trImages, trLabel, tsImages, tsLabel

**Comment by avish1993** [comment]
This function loads the train and test splits (images and labels) of the dataset saved in the form of numpy files and returns them. You can replace this function with your own data loading function.

**Comment by bleakie** [comment]
But how can I conduct a pre-training model test? There's only training in main.py, no testing.

**Comment by avish1993** [comment]
I have added a test.py file for the same.

**Comment by bleakie** [comment]
can you open the pre-model？ Thanks！

**Comment by bleakie** [comment]
can you release gen_epoch800.h5&disc_epoch800.h5？
