### ISSUE TITLE
Make .npy file to train

### ISSUE THREAD

**Issue by kycocotree** [avish1993/PosIX-GAN#2]
Can you give me the images.npy and labels.npy files sample ??
or explain more detail.

ex) 100 images (224x224x3) 
make .npy files -> 100 x 224 x 224 x 3 ??? 
and labels -> degree ?? like 15, 30.....

**Comment by ujjawalcse** [comment]
Thank you very much for making this fantastic work public.
Can I get more information about the data preparation.
Please share the data preparation code section if possible.

**Comment by avish1993** [comment]
The images for each of the 9 decoders were hand-separated for evaluation of PMSE loss. Thus, the trivial data preparation code simply read all images in a folder and save it into an npy file. The same code was run 9 times for the 9 different folders. Please go through the paper and this repository for details for data preparation.
