### ISSUE TITLE
Data Content Detail Sample

### ISSUE THREAD

**Issue by ujjawalcse** [avish1993/PosIX-GAN#3]
Hi Avishek Sir, Thanks for making the code public. I'm trying to prepare dataset as you said.
1.trImages.npy contains images belonging to different poses(different angles)
2.trLabel.npy contains corresponding one-hot-encoded labels
3.Above two steps are also followed for tsImages.npy and tsLabel.npy
4. For PMSE evaluation, nine files of images with specific pose and nine corresponding label files.
    for example,41_ims.npy contain images with 41 degree pose and 41_lbls.npy contain only 1's for all 
    corresponding images because all images belong to same pose.

But ,I'm getting error while training . my code lines containing labels file are producing error.
Please give some more details about the data preparation or data sample if possible.
----------------------------------------------------------------------------------------------------
 File "main.py", line 142, in <module>
    trainer.train(epochs, batches_per_epoch, batch_size, gamma,path='./PosIX-GAN                                                                                                             _weights')
  File "/home/ubuntu/PosIX-GAN-master/train.py", line 210, in train
    y1b.append(np.where(y_1l == el)[0][0])
IndexError: index 0 is out of bounds for axis 0 with size 0
--------------------------------------------------------------------------------------------------------
Please help sir.

**Comment by avish1993** [comment]
The label files contains the one-hot encoding of the subject ids for each specific pose. Also, I have mentioned before, there should be at least one sample of every subject in each pose-specific npy files (image and label). The error most probably indicates the absence of images of some subjects from some of the pose-specific npy files. Please take care of that.

**Comment by ujjawalcse** [comment]
Thank you very much.
I'll take care of that you said.
Now I'm going to rebuild my dataset.
Thanks once again.
